name       : rambox-pro
version    : 1.4.1
release    : 6
source     :
    - https://github.com/ramboxapp/download/releases/download/v1.4.1/RamboxPro-1.4.1-linux-x64.deb : d1dd2a250d8cf7d309b727128187712839575d33461f49f8a9d35e9d4ecc99e5
homepage   : https://rambox.pro
license    : https://rambox.pro/#eula
strip      : no
component  : system.utils
summary    : Rambox
description: |
    The all-in-one workspace browser.
builddeps  :
  - libgtk-3
  - libnotify
  - libnss
  - libxtst
  - xdg-utils
  - libappindicator
  - libsecret
rundeps    :
  - libgtk-3
  - libnotify
  - libnss
  - libxtst
  - xdg-utils
  - libappindicator
  - libsecret
setup      : |
    ar xf $sources/RamboxPro-${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R opt $installdir/opt/
    cp -R usr $installdir/usr/