name       : skype
version    : 8.65.0.78
release    : 11
source     :
    - https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.65.0.78_amd64.deb : 9026f043697d7d0783e7232701a868229d9a91e91dc0ae86509732c1c7bf0c13
homepage   : https://www.skype.com/
license    : Copyright (c) 2019 Skype and/or Microsoft
strip      : no
component  : network.im
summary    : Skype
description: |
    Skype keeps you together. Call, message and share with others.
builddeps  :
    - libnss
    - libatk
    - glibc
    - libcairo
    - pycups
    - libgcc
    - libgtk-3
    - libnspr
    - libsecret
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxrandr
    - libxrender
    - libstdc++
    - libdbusmenu
    - gnome-keyring
    - libxtst
rundeps    :
    - libnss
    - libatk
    - glibc
    - libcairo
    - pycups
    - libgcc
    - libgtk-3
    - libnspr
    - libsecret
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxrandr
    - libxrender
    - libstdc++
    - libdbusmenu
    - gnome-keyring
    - libxtst
setup      : |
    ar xf $sources/skypeforlinux_${version}_amd64.deb
    tar xf data.tar.xz
install    : |
    mkdir -p $installdir/usr/
    cp -R opt $installdir/opt/
    cp -R usr/{bin,share} $installdir/usr/