name       : 
version    : 
release    : 1
source     :
    - https://github.com/tom-james-watson/breaktimer-app/releases/download/v0.7.7/BreakTimer.deb : 98e9714521bbee6ae4d2b5166a4f79b40fd43d116ad6994d9fbb49cdf2692c04
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
