name       : ramboxpro-1.4.1-linux
version    : 
release    : 1
source     :
    - https://github.com/ramboxapp/download/releases/download/v1.4.1/RamboxPro-1.4.1-linux-x64.deb : d1dd2a250d8cf7d309b727128187712839575d33461f49f8a9d35e9d4ecc99e5
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
