name       : insync_3.3.3.40905
version    : 
release    : 1
source     :
    - http://s.insynchq.com/builds/insync_3.3.3.40905-bionic_amd64.deb : ab1c2e07eb0c45e9f01b4eef25aafe9c08f9f82064167510065907ccd8224a0b
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
