name       : ocenaudio
version    : 3.9.7
release    : 8
source     :
    - https://www.ocenaudio.com/downloads/index.php/ocenaudio_debian64.deb : 0e01452661ab1cee66d772dc58237bff568dd79071368a3368bc34b94a73c656
homepage   : https://www.ocenaudio.com/
license    : Copyright © 2015 ocenaudio
strip      : no
component  : network.clients
summary    : Ocenaudio
description: |
    Ocenaudio is a fast, cross-platform audio editor.
builddeps  :
  - gconf
  - jack-audio-connection-kit
rundeps    :
  - gconf
  - jack-audio-connection-kit
setup      : |
    ar xf $sources/ocenaudio*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R usr $installdir/usr/
    cp -R opt $installdir/opt/