name       : gitkraken
version    : 7.4.1
release    : 8
source     :
    - https://release.gitkraken.com/linux/gitkraken-amd64.deb : 9ba07a4b089767fe3bf553a2788b97ea1909a724f67d8410b18048e845eec3e8
homepage   : https://www.gitkraken.com
license    : EULA
strip      : no
component  : programming
summary    : GitKraken
description: |
    The downright luxurious Git client, for Windows, Mac and Linux.
builddeps  :
  - curl-gnutls
  - gconf
  - libgnome-keyring
  - libxscrnsaver
  - nodejs
rundeps    :
  - curl-gnutls
  - gconf
  - libgnome-keyring
  - libxscrnsaver
  - nodejs
setup      : |
    ar xf $sources/gitkraken*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R usr $installdir/usr/