name       : breaktimer
version    : 0.7.7
release    : 9
source     :
    - https://github.com/tom-james-watson/breaktimer-app/releases/download/v0.7.7/BreakTimer.deb : 98e9714521bbee6ae4d2b5166a4f79b40fd43d116ad6994d9fbb49cdf2692c04
homepage   : https://breaktimer.app/
license    : GPL-3.0-or-later
strip      : no
component  : system.utils
summary    : BreakTimer
description: |
    Manage periodic breaks.
builddeps  :
    - libgtk-3
    - libnotify
    - libnss
    - libxtst
    - xdg-utils
    - libappindicator
    - libsecret
rundeps    :
    - libgtk-3
    - libnotify
    - libnss
    - libxtst
    - xdg-utils
    - libappindicator
    - libsecret
setup      : |
    ar xf $sources/BreakTimer.deb
    tar xf data.tar.xz
install    : |
    mkdir -p $installdir
    cp -R opt $installdir/opt/
    cp -R usr $installdir/usr/