name       : emby-server
version    : 4.5.3.0
release    : 7
source     :
    - https://github.com/MediaBrowser/Emby.Releases/releases/download/4.5.3.0/emby-server-deb_4.5.3.0_amd64.deb : 0334f6c68bcd8a048e5dd0cd98d046159199c55aee67d5bc1621fa9c94648ac0
homepage   : https://emby.media
license    : © 2019 Emby LLC
strip      : no
component  : multimedia.video
summary    : Emby Server
description: |
    Emby Server is a personal media server with apps on just about every device.
builddeps  :
  - binutils
rundeps    :
  - binutils
setup      : |
    ar xf $sources/emby-server-deb_${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R etc $installdir/etc/
    cp -R opt $installdir/opt/
    cp -R usr $installdir/usr/