name       : wps-office
version    : 11.1.0.9719
release    : 5
source     :
    - https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9719/wps-office_11.1.0.9719.XA_amd64.deb : b3dc6494172b5d64261227049edc06e9b1f90556b6a0dbd43f0daa32648c46e7
    - https://github.com/IamDH4/ttf-wps-fonts/archive/master.zip : 6ad69800de95ea7f59129c233a80fda529e6a1b705e5f83330dd7ff96028dcb7
homepage   : https://www.wps.com/
license    : http://wps-community.org/license.md
strip      : no
component  : office
summary    : WPS Office, is an office productivity suite.
description: |
    WPS Office including Writer, Presentation and Spreadsheets, is a powerful office suite, which is able to process word file, produce wonderful slides, and analyze data as well. It is deeply compatible with all of the latest Microsoft Office file formats. It can easily open and read the documents created with Microsoft Office. This is the Linux version, and it's now a TESTING package.
builddeps  :
  - glibc
  - pycups
  - libglu
  - libsm
  - libxrender
  - libfontenc
  - libxext
  - libxcb
  - libgtk-2
  - unzip
rundeps    :
  - glibc
  - pycups
  - libglu
  - libsm
  - libxrender
  - libfontenc
  - libxext
  - libxcb
  - libgtk-2
setup      : |
    ar xf $sources/wps-office_${version}*
    tar xf data.tar*
    unzip $sources/master.zip
install    : |
    mkdir -p $installdir/usr
    mkdir -p $installdir/usr/share/fonts
    cp -R opt $installdir/opt/
    cp -R usr/{bin,share} $installdir/usr/
    cp -R ttf-wps-fonts-master/*.ttf $installdir/usr/share/fonts
    cp -R ttf-wps-fonts-master/*.TTF $installdir/usr/share/fonts
