name       : bitwig-studio
version    : 3.3
release    : 7
source     :
    - https://downloads.bitwig.com/stable/3.3/bitwig-studio-3.3.deb : 9baaf783c7d8ab28ccec29115d95df56a3722f642713688f0224751d3bda9d04
homepage   : https://bitwig.com
license    : © Bitwig GmbH 2018. All rights reserved.
strip      : no
component  : multimedia.audio
summary    : Music production system for production, remixing and performance.
description: |
    Music production system for production, remixing and performance.
builddeps  :
  - alsa-lib
  - jack-audio-connection-kit
  - libbsd
  - openjdk-8
  - xcb-util-wm
  - xdg-utils
  - zenity
rundeps    :
  - alsa-lib
  - jack-audio-connection-kit
  - libbsd
  - openjdk-8
  - xcb-util-wm
  - xdg-utils
  - zenity
setup      : |
    ar xf $sources/bitwig-studio-${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R opt $installdir/opt/
    cp -R usr $installdir/usr/