name       : libhandy
version    : 1.0.3
release    : 4
source     :
    - https://gitlab.gnome.org/GNOME/libhandy/-/archive/1.0.3/libhandy-1.0.3.tar.gz : 80c7f015b8ed0888f0f6a5cb15015d120cdf0dfcacf9dddb06d4e93bd8ffef1f
license    : LGPL-2.1+
component  : desktop.gnome
summary    : The Handy Library
description: |
    The Handy Library
builddeps  :
   - pkgconfig(gladeui-2.0)
   - pkgconfig(glib-2.0)
   - pkgconfig(gio-2.0)
   - pkgconfig(gmodule-2.0)
   - pkgconfig(gtk+-3.0)
   - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
