name       : plexmediaserver
version    : 1.21.0.3711
release    : 20
source     :
    - https://downloads.plex.tv/plex-media-server-new/1.21.0.3711-b509cc236/debian/plexmediaserver_1.21.0.3711-b509cc236_amd64.deb : cb7aa879e1a7df7ff1207acde1bbeffa24a0d1c9da611bfe54ea9e3118abfa47
homepage   : https://plex.tv
license    : https://plex.tv/legal
strip      : no
component  : multimedia.video
summary    : Plex Media Server
description: |
    Plex organizes all of your personal media so you can easily access and enjoy it.
builddeps  :
  - binutils
rundeps    :
  - binutils
setup      : |
    ar xf $sources/plexmediaserver_${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir/usr
    mkdir -p $installdir/opt
    install -Dm00644 $pkgfiles/plexmediaserver.conf $installdir/%libdir%/sysusers.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.tmpfile $installdir/%libdir%/tmpfiles.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.service $installdir/%libdir%/systemd/system/plexmediaserver.service
    cp -R usr/share $installdir/usr/
    cp -R usr/lib/plexmediaserver $installdir/opt/