name       : slack-desktop
version    : 4.11.3
release    : 4
source     :
    - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.11.3-amd64.deb : 03b7fbc8d2f3cdc70be8533dfb09a6fd3e7c2f428e97df27830b0712f479a67c
homepage   : https://slack.com
license    : © Copyright 2020 Slack Technologies, Inc.
strip      : no
component  : network.im
summary    : Slack Desktop
description: |
    Slack Desktop
builddeps  :
    - gconf
    - gvfs
    - hunspell-en
    - libgnome-keyring
    - libgtk-2
    - libxscrnsaver
rundeps    :
    - gconf
    - gvfs
    - hunspell-en
    - libgnome-keyring
    - libgtk-2
    - libxscrnsaver
setup      : |
    ar xf $sources/slack-desktop-${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir/usr/
    cp -R etc $installdir/etc/
    cp -R usr/{bin,lib,share} $installdir/usr/